name: Ping Healthcheck
# Updated 2026-06-20

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Reset Site
        env:
          SECRET_TOKEN: ${{secrets.SECRET_TOKEN}}
        run: |
          curl -H "X-Reset-Token: $SECRET_TOKEN" --max-time 90 --fail --silent --show-error \
          https://saltly.onrender.com/reset